name: Lint Helm chart
on:
  pull_request:
    branches:
      - master
      - develop
      - bugfix

jobs:
  lint:
    name: Lint chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.4.0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Configure Helm repos
        run: |-
             helm repo add bitnami https://charts.bitnami.com/bitnami
             helm dependency list ./deploy/kubernetes/charts
             helm dependency update ./deploy/kubernetes/charts

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Determine target branch
        id: ct-branch-target
        run: |
          if [ ! -z ${GITHUB_BASE_REF} ]; then
            echo "ct-branch=${GITHUB_BASE_REF}" >> $GITHUB_ENV
          else
            echo "ct-branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --target-branch ${{ env.ct-branch}})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --target-branch ${{ env.ct-branch }}
#        if: ${{ env.changed == 'true' }}
